const Map<String, String> mimeTypes = {
  "apng": "image/apng",
  "bmp": "image/bmp",
  "exr": "image/x-exr",
  "gif": "image/gif",
  "ico": "image/x-icon",
  "jpeg": "image/jpeg",
  "jpg": "image/jpeg",
  "png": "image/png",
  "ps": "application/postscript",
  "svg": "image/svg+xml",
  "swf": "application/x-shockwave-flash",
  "tif": "image/tiff",
  "tiff": "image/tiff",
  "webp": "image/webp",
};
