enum HighlightColor {
  black,
  blue,
  cyan,
  darkBlue,
  darkCyan,
  darkGray,
  darkGreen,
  darkMagenta,
  darkRed,
  darkYellow,
  green,
  lightGray,
  magenta,
  none,
  red,
  white,
  yellow,
}

enum LineBreakClearLocation { all, left, none, right }

enum LineBreakType { column, page, textWrapping }

enum LineRule { auto, exact, atLeast }

enum PageBorderDisplay { allPages, firstPage, notFirstPage }

enum PageBorderSide { top, bottom, left, right }

enum PageOrientation { landscape, portrait }

enum PageNumberingFormat {
  cardinalText,
  decimal,
  decimalEnclosedCircle,
  decimalEnclosedFullstop,
  decimalEnclosedParen,
  decimalZero,
  lowerLetter,
  lowerRoman,
  none,
  ordinalText,
  upperLetter,
  upperRoman,
}

enum ParagraphBorderSide { top, bottom, left, right, between, bar }

enum ParagraphBorderStyle {
  nil,
  none,
  single,
  thick,
  double,
  dotted,
  dashed,
  dotDash,
  dotDotDash,
  triple,
  thinThickSmallGap,
  thickThinSmallGap,
  thinThickThinSmallGap,
  thinThickMediumGap,
  thickThinMediumGap,
  thinThickThinMediumGap,
  thinThickLargeGap,
  thickThinLargeGap,
  thinThickThinLargeGap,
  wave,
  doubleWave,
  dashSmallGap,
  dashDotStroked,
  threeDEmboss,
  threeDEngrave,
  outset,
  inset,
  apples,
  archedScallops,
  babyPacifier,
  babyRattle,
  balloons3Colors,
  balloonsHotAir,
  basicBlackDashes,
  basicBlackDots,
  basicBlackSquares,
  basicThinLines,
  basicWhiteDashes,
  basicWhiteDots,
  basicWhiteSquares,
  basicWideInline,
  basicWideMidline,
  basicWideOutline,
  bats,
  birds,
  birdsFlight,
  cabins,
  cakeSlice,
  candyCorn,
  celticKnotwork,
  certificateBanner,
  chainLink,
  champagneBottle,
  checkedBarBlack,
  checkedBarColor,
  checkered,
  christmasTree,
  circlesLines,
  circlesRectangles,
  classicalWave,
  clocks,
  compass,
  confetti,
  confettiGrays,
  confettiOutline,
  confettiStreamers,
  confettiWhite,
  cornerTriangles,
  couponCutoutDashes,
  couponCutoutDots,
  crazyMaze,
  creaturesButterfly,
  creaturesFish,
  creaturesInsects,
  creaturesLadyBug,
  crossStitch,
  cup,
  decoArch,
  decoArchColor,
  decoBlocks,
  diamondsGray,
  doubleD,
  doubleDiamonds,
  earth1,
  earth2,
  eclipsingSquares1,
  eclipsingSquares2,
  eggsBlack,
  fans,
  film,
  firecrackers,
  flowersBlockPrint,
  flowersDaisies,
  flowersModern1,
  flowersModern2,
  flowersPansy,
  flowersRedRose,
  flowersRoses,
  flowersTeacup,
  flowersTiny,
  gems,
  gingerbreadMan,
  gradient,
  handmade1,
  handmade2,
  heartBalloon,
  heartGray,
  hearts,
  heebieJeebies,
  holly,
  houseFunky,
  hypnotic,
  iceCreamCones,
  lightBulb,
  lightning1,
  lightning2,
  mapPins,
  mapleLeaf,
  mapleMuffins,
  marquee,
  marqueeToothed,
  moons,
  mosaic,
  musicNotes,
  northwest,
  ovals,
  packages,
  palmsBlack,
  palmsColor,
  paperClips,
  papyrus,
  partyFavor,
  partyGlass,
  pencils,
  people,
  peopleWaving,
  peopleHats,
  poinsettias,
  postageStamp,
  pumpkin1,
  pushPinNote2,
  pushPinNote1,
  pyramids,
  pyramidsAbove,
  quadrants,
  rings,
  safari,
  sawtooth,
  sawtoothGray,
  scaredCat,
  seattle,
  shadowedSquares,
  sharksTeeth,
  shorebirdTracks,
  skyrocket,
  snowflakeFancy,
  snowflakes,
  sombrero,
  southwest,
  stars,
  starsTop,
  stars3d,
  starsBlack,
  starsShadowed,
  sun,
  swirligig,
  tornPaper,
  tornPaperBlack,
  trees,
  triangleParty,
  triangles,
  tribal1,
  tribal2,
  tribal3,
  tribal4,
  tribal5,
  tribal6,
  twistedLines1,
  twistedLines2,
  vine,
  waveline,
  weavingAngles,
  weavingBraid,
  weavingRibbon,
  weavingStrips,
  whiteFlowers,
  woodwork,
  xIllusions,
  zanyTriangles,
  zigZag,
  zigZagStitch,
}

enum ReferenceType { first, defaultType, even }

enum RestartLineNumber { continuous, newPage, newSection }

enum SectType {
  continuous,
  evenPage,
  nextColumn,
  nextPage,
  oddPage,
}

enum SectVerticalAlign {
  both,
  bottom,
  center,
  top,
}

enum ShadingPatternStyle {
  nil,
  clear,
  solid,
  horzStripe,
  vertStripe,
  reverseDiagStripe,
  diagStripe,
  horzCross,
  diagCross,
  thinHorzStripe,
  thinVertStripe,
  thinReverseDiagStripe,
  thinDiagStripe,
  thinHorzCross,
  thinDiagCross,
  pct5,
  pct10,
  pct12,
  pct15,
  pct20,
  pct25,
  pct30,
  pct35,
  pct37,
  pct40,
  pct45,
  pct50,
  pct55,
  pct60,
  pct62,
  pct65,
  pct70,
  pct75,
  pct80,
  pct85,
  pct87,
  pct90,
  pct95,
}

enum TabLeader {
  dot,
  heavy,
  hyphen,
  middleDot,
  none,
  underscore,
}

enum TabStyle { bar, center, clear, decimal, end, num, start, left, right }

enum TextAlignment { left, right, center, distribute, justify, start, end }

enum TextArtStyle {
  emboss,
  imprint,
  outline,
  shadow,
}

enum TextEffect {
  blinkBackground,
  lights,
  antsBlack,
  antsRed,
  shimmer,
  sparkle,
  none,
}

enum UnderlineStyle {
  dash,
  dashDotDotHeavy,
  dashDotHeavy,
  dashedHeavy,
  dashLong,
  dashLongHeavy,
  dotDash,
  dotDotDash,
  dotted,
  dottedHeavy,
  double,
  none,
  single,
  thick,
  wave,
  wavyDouble,
  wavyHeavy,
  words,
}

enum VerticalAlignStyle { baseline, subscript, superscript }

enum VerticalTextAlignment {
  auto,
  baseline,
  bottom,
  center,
  top,
}
